### ISSUE TITLE
Contract page for project 404s

### ISSUE THREAD

**Issue by dvargasfuertes** [dvargas92495/floss#39]

**Comment by Pretuer** [comment]
https://neilpatel.com/blog/how-to-create-a-spectacular-404-error-page-with-12-examples/

https://medium.com/designer-recipes/how-to-make-a-custom-404-error-page-for-your-website-1af37a8b20d1

This should help you build it!

**Comment by dvargasfuertes** [comment]
Thanks for the links! This task was actually to solve a 404, not build one haha
